tots = {0: "Expenses", 1: "Incomes"}
toes = {
    0: "Cost of goods sold",
    1: "Selling and distribution expenses",
    2: "Operating, general and administrative expenses",
    3: "Salaries, wages, and benefits",
    4: "Rent expense",
    5: "Cost of utilities",
    6: "Provisions and impairments",
    7: "Depreciation expense",
    8: "Amortization expense",
    9: "Research and development costs",
    10: "Printing and stationery expense",
    11: "Staff traveling expense",
    12: "Repair and maintenance expense",
    13: "Insurance cost",
    14: "Legal and professional charges",
    15: "Communication expense",
    16: "Miscellaneous expenses",
    17: "Finance cost",
    18: "Taxation",
}

tois = {
    0: "Alimony",
    1: "Annuity payments",
    2: "Bonuses",
    3: "Business income",
    4: "Capital gains",
    5: "Child support",
    6: "Commissions",
    7: "Consulting fees",
    8: "Cryptocurrency gains",
    9: "Dividend income",
    10: "Estate income",
    11: "Farm income",
    12: "Fellowship income",
    13: "Foreign exchange gains",
    14: "Foreign income",
    15: "Franchise income",
    16: "Freelance income",
    17: "Gambling winnings",
    18: "Interest income",
    19: "Lawsuit settlements",
    20: "Licensing income",
    21: "Life insurance cash value withdrawals",
    22: "Partnership income",
    23: "Patent income",
    24: "Pension income",
    25: "Prizes & awards",
    26: "Rental income",
    27: "Residual income",
    28: "Retirement account withdrawals",
    29: "Royalties",
    30: "Royalty trust income",
    31: "Salary",
    32: "Scholarships and grants",
    33: "Self-employment income",
    34: "Severance pay",
    35: "Social security benefits",
    36: "Stock options income",
    37: "Tips",
    38: "Trust income",
    39: "Unemployment compensation",
    40: "Wages",
    41: "Workers compensation",
}

tots = {0: toes, 1: tois}
